### ISSUE TITLE
Rocket Cannot Connect to Socket

### ISSUE THREAD

**Issue by nabulator** [anttihirvonen/moonlander#1]
Running Processing 3.2.2 on linux. Latest compiled rocket with 0.9 v of moonlander. 
I couldn't establish a connection with rocket. 
Turning on finest logging shows me that the connection is established, the greeting sent but moonlander cannot read greetings from server.

I think Rocket receives the greetings since everytime I connect, I get a status that appears "not connected"

EDIT: seems to be connection reset exception...

**Comment by anttihirvonen** [comment]
Sorry to take so long, but I just integrated a patch to fix this issue. Can you check if it works now?

**Comment by anttihirvonen** [comment]
I assume this has been fixed now. Closing the issue.
